### ISSUE TITLE
Still show the customed context menu after right-clicking outside the element 

### ISSUE THREAD

**Issue by tatekicct** [steviebaa/mui-nested-menu#24]
When I tried the sample (https://mui-nested-menu.vercel.app/context-menu),
I found the weired behavior (maybe bug).

After right-clicking the "Right Click Me!", the customed context menu pops up.
This is the normal behavior we have expected.
However right-clicking again outside the "Right Click Me" element while the customed context menu is showing up, there still be the customed one, not the default one.

I don't know whether this is bug or not.
Could you confirm this problem? 
Thank you.

**Comment by steviebaa** [comment]
Hey @tatekicct, yeah I'd call this one a bug I think. I think intuitive behaviour would be:

- while the context menu is open, if you right click again somewhere else in the element that is wrapped in the context menu then it should just move the menu to that point. 
- while the context menu is open, if you right click again somewhere else **outside** the element that is wrapped in the context menu, then it should probably close.

Bit of a tricky one. My approach would be to:
1. Make sure the ref on line 55 has been provided, if not then create a ref at the top of the component so there is one.
2. Then in `handleMouseDown`, around line 29 we can get the context wrapper bounds something like `const wrapperBounds = ref.current.getBoundingClientRect()` and check if the mouse down event coordinates are inside that rect. If not then return early else carry on setting the position. 

https://github.com/steviebaa/mui-nested-menu/blob/main/src/mui-nested-menu/components/ContextMenu.tsx#L53-L63

If anyone would like to contribute open a PR and let us know here, otherwise I'll get around to it this weekend perhaps.

**Comment by steviebaa** [comment]
Appears to be fixed. [Visit Preview](https://mui-nested-menu-git-contextmenu-click-bounds-steviebaa.vercel.app/)

Feel free to check it out. Ill merge and deploy tomorrow.

**Comment by steviebaa** [comment]
Deployed as [version 2.1.3](https://www.npmjs.com/package/mui-nested-menu/v/2.1.3)
